// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmrnbmmqadndfpmjljsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcm5ibW1xYWRuZGZwbWpsanNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDM4NzgsImV4cCI6MjA2NzI3OTg3OH0.lh8fflVQq5WKqWx_dSE23EJ5V2HUiJ_PHy80AClgBiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});